version: "3.7"

services:

  module-service:
    image: docker.nexus.archi-lab.io/archilab/prox-module-service
    ports:
      - "9001:9001"
    restart: always
    networks:
      - prox
      - module-db

  module-db:
    image: postgres:11.3-alpine
    volumes:
      - module-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=module-service
      - POSTGRES_PASSWORD=module-service
      - POSTGRES_DB=module-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - module-db

volumes:
  module-db-data:

networks:
  prox:
    external: true
  module-db:
