version: '3.5'


# Microservice backend

services:

  # Microservice database
  module-db:
    image: postgres:10.1
    restart: always
    networks:
      - module-service-db
    environment:
      - POSTGRES_PASSWORD=_PTBModuleService_2018
      - POSTGRES_USER=module_service
      - POSTGRES_DB=module_service
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx128m
    volumes:
      - module-data:/var/lib/postgresql/data

  # Microservice instance
  module-service:
    image: module-service
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - module-db
    restart: always
    networks:
      - module-service-db
#      - ptb-infrastructure

# Microservice network
networks:
  module-service-db:
    name: ptb_module-net

## Connect service with api-gateway and service discovery
#  ptb-infrastructure:
#    external:
#      name: ptb_infra-net

# Microservice storage
volumes:
  module-data:
