version: '3'

services:
  module-service:
    image: ptb-gp-ss2019.archi-lab.io/module-service
    ports:
      - "9001:9001"
    restart: always
    networks:
      - ptb
      - module-db

  module-db:
    image: postgres:11.2-alpine
    volumes:
      - module-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=module-service
      - POSTGRES_PASSWORD=module-service
      - POSTGRES_DB=module-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - module-db

volumes:
  module-db-data:

networks:
  ptb:
    external: true
  module-db:

