version: '3'

services:
  module-service:
    image: ptb.archi-lab.io/module-service
    ports:
      - "9003:9003"
    restart: always
    networks:
      - ptb-gp-ss2019
      - module-db

  module-db:
    image: postgres:11.2-alpine
    volumes:
      - module-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=module-service
      - POSTGRES_PASSWORD=module-service
      - POSTGRES_DB=module-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - module-db

volumes:
  module-db-data:

networks:
  ptb-gp-ss2019:
    external: true
  module-db:

