eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    password: module-service
    url: jdbc:h2:mem:testdb
    username: module-service
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      dialect: H2DialectCustom
  flyway:
    enabled: false
