eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
importHops:
  delay:
    hasData:
      minutes: 1440
    hasNoData:
      seconds: 10
keycloak:
  auth-server-url: https://login.archi-lab.io/auth
  bearer-only: true
  cors: false
  principal-attribute: preferred_username
  realm: archilab
  resource: prox-module-service
server:
  port: 9001
  forward-headers-strategy: native
spring:
  application:
    name: module-service
  datasource:
    password: module-service
    url: jdbc:postgresql://module-db:5432/module-db
    username: module-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
